## Generated By AI
import redis
import json
import uuid
from faker import Faker
from datetime import datetime, timedelta

# -------------------------- 1. Redis Connection Configuration --------------------------
REDIS_CONFIG = {
    "host": "localhost",    # Your Redis host (default: localhost for local environment)
    "port": 6379,           # Redis default port
    "password": "",         # Your Redis password (leave empty if no password)
    "db": 2,                # Use DB 2 exclusively for sessions to avoid business conflicts
    "decode_responses": True  # Auto-decode responses to string for easier handling
}

# Connect to Redis
redis_client = redis.Redis(**REDIS_CONFIG)

# -------------------------- 2. Mock Data Generation Configuration --------------------------
GENERATE_COUNT = 1000  # Total number of session records to generate
USER_ID_RANGE = range(100, 501)  # User ID range: U100 - U500 (401 unique users for multi-session support)
DEVICE_TYPES = ["desktop", "mobile", "tablet", "smart_tv"]  # Supported device types
TIME_RANGE_DAYS = 7  # Session creation time range: within the last 7 days

# Initialize Faker (for generating realistic timestamps)
fake = Faker()
Faker.seed(42)  # Fixed seed for reproducible mock data

# -------------------------- 3. Generate 1000 Session Records --------------------------
def generate_session_data():
    print(f"Starting to generate {GENERATE_COUNT} Redis Session records...")
    
    for _ in range(GENERATE_COUNT):
        # 1. Generate unique session_id (UUID4 format to ensure no duplicates)
        session_id = str(uuid.uuid4())
        # 2. Randomly select device type from predefined list
        device_type = fake.random_element(elements=DEVICE_TYPES)
        # 3. Generate random user ID (format: U + numeric value)
        user_id = f"U{fake.random_element(elements=USER_ID_RANGE)}"
        # 4. Generate session creation time (random time within last 7 days, ISO 8601 format)
        created_at = fake.date_time_between(
            start_date=f"-{TIME_RANGE_DAYS}d",  # Start: 7 days ago
            end_date="now",                     # End: current time
            tzinfo=None
        ).isoformat() + "Z"  # Append 'Z' to match ISO 8601 standard in the example
        # 5. Generate last activity time (always after creation time, before current time)
        last_activity = fake.date_time_between(
            start_date=created_at.replace("Z", ""),  # Base on creation time
            end_date="now",
            tzinfo=None
        ).isoformat() + "Z"
        
        # Construct session data (exact match with your defined JSON structure)
        session_data = {
            "device_type": device_type,
            "user_id": user_id,
            "created_at": created_at,
            "last_activity": last_activity
        }
        
        # Write to Redis: Key = session:{session_id}, Value = JSON string
        redis_key = f"session:{session_id}"
        redis_client.set(redis_key, json.dumps(session_data, ensure_ascii=False))
        
        # Set session expiration: 7 days (consistent with time range, simulates temporary session)
        redis_client.expire(redis_key, 60 * 60 * 24 * 7)
    
    print(f"Data generation completed! {GENERATE_COUNT} session records written to Redis.")

# -------------------------- 4. Verify Generated Data (Optional) --------------------------
def verify_generated_data(count=5):
    print(f"\n=== Randomly checking {count} generated session records ===")
    # Fuzzy match all session keys
    session_keys = redis_client.keys("session:*")
    # Randomly select 'count' keys for verification
    sample_keys = fake.random_sample(elements=session_keys, length=min(count, len(session_keys)))
    
    for key in sample_keys:
        session_str = redis_client.get(key)
        session_data = json.loads(session_str)
        print(f"\nRedis Key: {key}")
        print(f"Session Data: {json.dumps(session_data, ensure_ascii=False, indent=2)}")

# -------------------------- 5. Execute Generation & Verification --------------------------
if __name__ == "__main__":
    # Generate mock session data
    generate_session_data()
    # Verify generated data (optional - comment out to skip verification)
    verify_generated_data(count=5)